### ISSUE TITLE
About condition on start-end pose when diffusion model sampling

### ISSUE THREAD

**Issue by ManUtdMoon** [zhouxian/act3d-chained-diffuser#12]
Dear authors,

Hi!

When I read the sampling part of `compute_trajectory` in [model/trajectory_optimization/diffusion_model.py](https://github.com/zhouxian/act3d-chained-diffuser/blob/main/model/trajectory_optimization/diffusion_model.py#L163), I am confused about the effect of `_use_goal_at_test`.

```python
# Condition on start-end pose
# ...
# end pose
if self._use_goal_at_test:
	for d in range(len(cond_data)):
		neg_len_ = -trajectory_mask[d].sum().long()
		cond_data[d][neg_len_ - 1] = goal_gripper[d]
		cond_mask[d][neg_len_ - 1:] = 1
cond_mask = cond_mask.bool()
```

Here are my question:
When *evaluating* the models, you do not overwrite the sampled trajectory with the end pose because the `_use_goal_at_test` is set to `False` [here](https://github.com/zhouxian/act3d-chained-diffuser/blob/main/online_evaluation/eval1.py#L104). Why not use the action predicted by Act3D here in evaluation to overwrite but use the predicted one by the diffusion model?

I am looking forward to your reply. Thank you for your time.

Regrards,
Dongjie

**Comment by nickgkan** [comment]
Hi,
We found that this performs better. The trajectory model implicitly models the end keypose as well. We found that this prediction is often better than Act3D's.

**Comment by ManUtdMoon** [comment]
> Hi, We found that this performs better. The trajectory model implicitly models the end keypose as well. We found that this prediction is often better than Act3D's.

Hi,
Got it! Thank you for your reply.

By the way, I came to another two questions during reading data processing. Specifically,
- In [`dataset_engine.py`](https://github.com/zhouxian/act3d-chained-diffuser/blob/main/datasets/dataset_engine.py#L214), the 5th element of an episode is a trajectory between two keyposes. However, in [`data_gen.py`](https://github.com/zhouxian/act3d-chained-diffuser/blob/main/data_preprocessing/data_gen.py#L157), the last element of an episode is `4`. Would you please specify the place where the trajectory is added?
- I wonder the `frame_ids` in an episode is _keyframe ids_ or id for _each normal frame_.

Thank you for your time.

Regards,
Dongjie

**Comment by nickgkan** [comment]
Hi, the frame_ids refer to keyframes (keyposes), the same dataset class is used for keyposes and trajectories. In case of trajectories, the model learns to predict a trajectory between two consecutive keyposes.

As for the data generation, we modified the shared script for that to store all steps between two keyframes (without storing the observations).

**Comment by ManUtdMoon** [comment]
> Hi, the frame_ids refer to keyframes (keyposes), the same dataset class is used for keyposes and trajectories. In case of trajectories, the model learns to predict a trajectory between two consecutive keyposes.
> 
> As for the data generation, we modified the shared script for that to store all steps between two keyframes (without storing the observations).

Hi, thank you for your reply. It addressed my questions well.

I wish you all the best!
