### ISSUE TITLE
Could you release the trained checkpoint for evaluation?

### ISSUE THREAD

**Issue by swords123** [zhouxian/act3d-chained-diffuser#13]
Hello, I am very interested in your work. Could you release the trained checkpoint for evaluation?

**Comment by nickgkan** [comment]
Hi,

You can now find updated train/test scripts and checkpoints in our codebase for our new project here https://github.com/nickgkan/3d_diffuser_actor. We include the checkpoint for Act3D as well.

That said, our new model outperforms Act3D by >16%, so check it out if you're interested! Please redirect your questions about Act3D and/or our new work on that repo.

Thank you for your interest in our work!
