### ISSUE TITLE
code got stuck in sampling

### ISSUE THREAD

**Issue by yuelei0428** [zhouxian/act3d-chained-diffuser#14]
When running the turn_tap dataset, the code got stuck in sample_ghost_points_uniform_sphere, because it can't find a point closer enough to the center (the lr norm > 1 for nearly all the points).

What's the recommend solution in this case? I afraid that directly changing the point selection threshold will result in bad performance.

**Comment by nickgkan** [comment]
Hi,
We never encountered this issue, so it is possible that some hyperparameter was set wrong in the first place. You can find our re-implementation of Act3D, train/test scripts and checkpoints in our new repo https://github.com/nickgkan/3d_diffuser_actor.
Thank you for your interest in our work. If you still encounter this issue, feel free to reopen this issue!
