### ISSUE TITLE
instructions.pkl issue

### ISSUE THREAD

**Issue by yuelei0428** [zhouxian/act3d-chained-diffuser#16]
In the instructions.pkl file, each task only has variation 1. Is this what's expected?

**Comment by nickgkan** [comment]
Hi,
For additional information on this issue, check this link https://github.com/nickgkan/3d_diffuser_actor?tab=readme-ov-file#optional-encode-language-instructions from our new repository. Also check out our new project 3D Diffuser Actor if you are interested!
Thanks for your interest in our work!
