### ISSUE TITLE
CoppeliaSim symlink error

### ISSUE THREAD

**Issue by atharvayeola** [zhouxian/act3d-chained-diffuser#19]
Hi. I'm using this paper for my research and currently reproducing the results. I came across this issue while installing PyRep; to be specific the below command:

" pip install -r requirements.txt; pip install -e .; cd .. "

Please see the below screenshot for more details.

![Screenshot from 2024-03-11 14-23-46](https://github.com/zhouxian/act3d-chained-diffuser/assets/76895421/f6841700-5e4d-48bc-8153-88dd1ba37c51)
![Screenshot from 2024-03-11 14-24-35](https://github.com/zhouxian/act3d-chained-diffuser/assets/76895421/f4a5a2f5-907b-499d-8e48-bd323766b693)

The command "pip install -e ." is what is causing troubles

**Comment by atharvayeola** [comment]
the file "libcoppeliaSim.so.1" is not available in the folder 
"./CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/"
So earlier it was present but it was corrupted so I deleted it. Could @zhouxian upload the file separately in the repo? Also need help with this urgently!
Thank you!!

**Comment by zhouxian** [comment]
Could you checkout instructions in https://github.com/nickgkan/3d_diffuser_actor?

**Comment by atharvayeola** [comment]
Ok great that helped!

**Comment by atharvayeola** [comment]
![image](https://github.com/zhouxian/act3d-chained-diffuser/assets/76895421/7e62821a-8cbe-49a3-b87c-bc2c95241208)

Apologies for reopening the issue, but I am getting the above error. Something seems off with PyRep. Any help would be appreciated!

PS: I followed every direction mentioned in https://github.com/stepjam/PyRep/blob/master/README.md#contributing and https://github.com/nickgkan/3d_diffuser_actor

**Comment by zhouxian** [comment]
I think @nickgkan has a better idea here

**Comment by atharvayeola** [comment]
Hey @nickgkan , I'd appreciate if you could take some time out to help me resolve the above error. There seems to be an issue with regards to pyrep module. 
I require help on this to meet an urgent deadline. 
Thank you!

**Comment by nickgkan** [comment]
Hi @Atharva-cloud, it seems that you successfully installed the library, is that correct?

The last error you shared is on the data generation script, it seems that the offset argument has been removed but the command still uses it. Apologies for that, probably I missed the update on the command when resolving some issues on the generation script. Remove that argument and try again.

Also, please let us know the setup you'd like to test. If you PerAct multi-task, you can directly download the data (no need to run the generation script), see here https://github.com/nickgkan/3d_diffuser_actor/blob/master/docs/DATA_PREPARATION_RLBENCH.md.
