### ISSUE TITLE
Multi-task Training

### ISSUE THREAD

**Issue by TeleeMa** [zhouxian/act3d-chained-diffuser#2]
Hi,

I found all the codes (Act3D & DiffusionTracjectory) use single-task training, however, multi-task performance are reported in your paper. So how to train the models in multi-task setting?

Thanks.

**Comment by nickgkan** [comment]
Hi, thanks for your interest in our work.
The `--tasks` argument accepts a list of tasks. You can use something like `--tasks TASK1 TASK2 TASK3`.
