### ISSUE TITLE
Distributed training not working

### ISSUE THREAD

**Issue by ishikasingh** [zhouxian/act3d-chained-diffuser#20]
Hi, thanks for releasing the code!

I am trying to do distributed multi-gpu training, but the process always just launches on one gpu even though `torch.cuda.device_count()>1` as printed by `main_kepose.py` script.

Is there a parameter I need to change? Or define world size somewhere. 
I get `torch.distributed.get_world_size() = 1` right now.

PS. I am running on a cluster with user level privilege, not sure if that makes a difference.

**Comment by nickgkan** [comment]
This was answered offline, but for anyone coming here in the future, please use the 3D Diffuser Actor's implementation of Act3D to train/test https://github.com/nickgkan/3d_diffuser_actor.
