### ISSUE TITLE
AttributeError: 'Act3D' object has no attribute 'prepare_action

### ISSUE THREAD

**Issue by YuquanDeng** [zhouxian/act3d-chained-diffuser#3]
Hi there, I am running the evaluation through `bash online_evaluation/eval_single_task_mandoo.sh`. However, I met an AttributeError as shown below:
![image](https://github.com/zhouxian/act3d-chained-diffuser/assets/88260334/b9ab861a-d692-4649-9aff-a255c45e2c84)

The [model class Act3D](https://github.com/zhouxian/act3d-chained-diffuser/blob/9ffc6bc2d8dce71f12d3a9d8de9e4f4591da7164/model/keypose_optimization/act3d.py#L507) does not contain the method `prepare_action`.

**Comment by nickgkan** [comment]
Hi, indeed there were some API changes in the code release. We're working on this and will provide an update soon.

**Comment by ZXP-S-works** [comment]
Hi nickgkan,

Do you have any update on this? I am trying to benchmarking your method.

Best,
XP

**Comment by nickgkan** [comment]
Hi, sorry for the delay, I'll resolve this issue in the next days.

**Comment by nickgkan** [comment]
Hi everyone, sorry it took so long due to various reasons. This is fixed now, please pull the updated version of the code - the only change is under online_evaluation/utils_with_rlbench.py.

We're working on fixing the other Github issues, thanks for letting us know
