### ISSUE TITLE
Campatibility issues

### ISSUE THREAD

**Issue by ZXP-S-works** [zhouxian/act3d-chained-diffuser#5]
Hi Zhuoxian,

Amazing work!

I tried to run your code follows the steps in README, however, I got some errors with module "tap". Would you mind to tell me which tap do you installed and how do installed it?

Here are some error messages:
```
ModuleNotFoundError: No module named 'tap'
```

``` 
   except MemcachedError, e:
                         ^
SyntaxError: invalid syntax
```

```
    import exceptions
ModuleNotFoundError: No module named 'exceptions'
```

Best,
XP

**Comment by zhouxian** [comment]
Maybe @nickgkan have some instruction on this?

**Comment by ZXP-S-works** [comment]
Hi Zhuoxian, lucky I found a Chinese blog solved this problem: https://blog.csdn.net/CCCDeric/article/details/129292190 --it needs to make several manual changes on 'tap's source code.

**Comment by nickgkan** [comment]
Hi,
For everyone revisiting this issue in the future, "tap" here should be installed as
`pip install typed-argument-parser`
Please don't install the library "tap".

**Comment by ZXP-S-works** [comment]
Hi nickgkan,

Thanks for pointing out that!

XP
